spring:
  application:
    name: clubActiv
  datasource:
    url: jdbc:postgresql://localhost:5432/activeDB
    username: postgres
    password: qwerty007
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

key:
  access: rq2fK1dVk9TNRg3aQPhEWSVFESp+DEmoY0KdSn6hYGY=
  refresh: u1DiTkT2eOnqMhLwIoNAQ9aoCsmJqFk1HVRM9r8Tcfs=